version: 1.0.{build}
image: Visual Studio 2017
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet pack
test_script:
- cmd: dotnet test .\test\xApiFilterTest\xApiFilterTest.csproj
artifacts:
- path: '**\*.nupkg'
  name: NuGetAppV
